# api_key : sk-ELuUc9RT4WRyX183Q16uaFbjKc7JCKBslXROZ7mo7hXgIwxF
# api_base : https://api.hunyuan.cloud.tencent.com/v1
# api_model : hunyuan-turbo

api_key : sk-fMklCXGiJbGJYmg06TTVwGKNlXXe6sRCP9RwYh8AUFm01B7K
api_base : https://api.moonshot.cn/v1
api_model : moonshot-v1-8k